version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: test-php
    ports:
      - 9000
    tty: true
    volumes:
      - ./Test/symfony:/var/www
    networks:
      - internal

  nginx:
    build:
      context: ./docker/nginx
    container_name: test-nginx
    tty: true
    ports:
      - 8666:80
    volumes:
      - ./Test/symfony:/var/www
      - ./docker/nginx/conf/test.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

networks:
  internal:
